on:
  push:
    branches:
      - main
  pull_request:

jobs:
  icpx202310:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        wget -q -O install.sh https://registrationcenter-download.intel.com/akdlm/IRC_NAS/89283df8-c667-47b0-b7e1-c4573e37bd3e/l_dpcpp-cpp-compiler_p_2023.1.0.46347_offline.sh
        bash install.sh -s -a -s --action install --eula accept
        sudo rm -rf /usr/lib/gcc/x86_64-linux-gnu/{9,10,11}
    - name: compile
      run: |
        source ~/intel/oneapi/setvars.sh
        icpx -v -c test.cpp

  icpx202300:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: |
        wget -q -O install.sh https://registrationcenter-download.intel.com/akdlm/irc_nas/19123/l_dpcpp-cpp-compiler_p_2023.0.0.25393_offline.sh
        bash install.sh -s -a -s --action install --eula accept
    - name: compile
      run: |
        source ~/intel/oneapi/setvars.sh
        icpx -v -c test.cpp

  setup_202300:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rscohn2/setup-oneapi@v0
      with:
        components: icx@2023.0.0
    - name: compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        icpx -v -c test.cpp

  setup_202310:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rscohn2/setup-oneapi@v0
      with:
        components: icx@2023.1.0
    - name: compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        icpx -v -c test.cpp
  
setup_202310_rm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rscohn2/setup-oneapi@v0
      with:
        components: icx@2023.1.0
    - name: compile
      run: |
        sudo rm -rf /usr/lib/gcc/x86_64-linux-gnu/{9,10,11}
        source /opt/intel/oneapi/setvars.sh
        icpx -v -c test.cpp
  
  setup_202310_CC:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rscohn2/setup-oneapi@v0
      with:
        components: icx@2023.1.0
    - name: compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        export CC=ICX
        icpx -v -c test.cpp
    